#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 4
console_title_template = "{{if .Root}}(Admin){{end}} {{.PWD}}"

[upgrade]
  source = "cdn"
  interval = "168h"
  auto = false
  notice = false

[transient_prompt]
  template = "❯ "
  foreground = "lightMagenta"
  foreground_templates = ["{{ if gt .Code 0 }}lightRed{{ end }}"]

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    template = "{{ .UserName }} "
    foreground = "lightRed"
    type = "session"
    style = "plain"

  [[blocks.segments]]
    template = "{{ .Path }} "
    foreground = "cyan"
    type = "path"
    style = "plain"

    [blocks.segments.options]
      style = "full"

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    type = "jujutsu"
    style = 'plain'
    foreground = "lightYellow"

    [blocks.segments.options]
      fetch_status = true
      ignore_working_copy = false
      fetch_ahead_counter = true
      ahead_icon = "⇡"

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    template = " {{ .FormattedMs }} "
    foreground = "lightGreen"
    type = "executiontime"
    style = "plain"

    [blocks.segments.options]
      style = "austin"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = "❯ "
    foreground = "lightMagenta"
    type = "status"
    style = "plain"
    foreground_templates = ["{{ if gt .Code 0 }}lightRed{{ end }}"]

    [blocks.segments.options]
      always_enabled = true
