[tools]
usage = "latest"
carapace = "latest"
chezmoi = "latest"
devcontainer-cli = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
herdr = "latest"
lazydocker = "latest"
jj = "latest"
jjui = "latest"
neovim = "latest"
node = "latest"
oh-my-posh = "latest"
ollama = "latest"
pi = "latest"
television = "latest"
tree-sitter = "latest"
yazi = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
"aqua:nushell/nushell" = "latest"
"github:fgrehm/crib" = "latest"
"aqua:zk-org/zk" = "latest"

[settings]
experimental = true
