# general
background = '#112641'         # Original Minischeme Navy
border_fg = '#3a475e'          # Selection/Black for subtle borders
text_fg = '#e2e98f'            # Ivory Yellow
dimmed_text_fg = '#606a7b'     # UI Grey

# input
input_text_fg = '#ff5f5f'      # High-Contrast Red for typing
result_count_fg = '#cc7e46'    # Orange for the count

# results
result_name_fg = '#42f7ff'     # Electric Blue
result_line_number_fg = '#ffc4ff' # Magenta for line numbers
result_value_fg = '#adb2bb'    # Light Grey/Blue for the content
selection_fg = '#fcffaa'       # Brightest Yellow for selection text
selection_bg = '#3a475e'       # Black/Navy for selection bar
match_fg = '#ff5f5f'           # High-Contrast Red for search matches

# preview
preview_title_fg = '#cc7e46'   # Orange for titles

# modes
channel_mode_fg = '#112641'    # Navy (on light background)
channel_mode_bg = '#ca6ecf'    # Cyan/Purple
remote_control_mode_fg = '#112641'
remote_control_mode_bg = '#9ff895' # Green
send_to_channel_mode_fg = '#42f7ff' # Electric Blue
