onboarding = false
[terminal]
default_shell = "zsh"

[theme]
name = "terminal"

[keys]
edit_scrollback = "prefix+shift+e"
open_notification_target = ""
help = "prefix+?"
settings = "prefix+s"
detach = "prefix+q"
reload_config = "prefix+shift+r"
workspace_picker = "prefix+w"
goto = "prefix+g"
new_workspace = "prefix+shift+n"
rename_workspace = "prefix+shift+w"
close_workspace = "prefix+shift+d"
new_tab = "prefix+c"
rename_tab = "prefix+shift+t"
previous_tab = "prefix+p"
next_tab = "prefix+n"
switch_tab = "prefix+1..9"
close_tab = "prefix+shift+x"
split_vertical = "prefix+v"
split_horizontal = "prefix+minus"
close_pane = "prefix+x"
zoom = "prefix+z"
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
cycle_pane_next = "prefix+tab"
cycle_pane_previous = "prefix+shift+tab"
rename_pane = "prefix+shift+p"
resize_mode = "prefix+r"
toggle_sidebar = "prefix+b"

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = true

[ui]
status_indicators = "symbols"

[[keys.command]]
key = "prefix+e"
type = "plugin_action"
command = "chmarax.herdr-nvim.toggle"

[[keys.command]]
key = "prefix+o"
type = "plugin_action"
command = "chmarax.herdr-nvim.pick-file"

[[keys.command]]
key = "prefix+alt+j"
type = "popup"
command = "cd \"$(herdr pane get \"$HERDR_ACTIVE_PANE_ID\" | jq -r .result.pane.foreground_cwd)\" && jjui"
description = "run jjui"
width = "80%"
height = "80%"

